### PR TITLE
Rebase to go-ethereum v1.8.22

### PR DESCRIPTION
**Pull request by seanjnkns**
Contributer address: 0xa2E85B0b8f7ed1569b5bBaf5aF74D07B65E0d538

This is incomplete, so DO NOT merge until v1.8.22 of go-ethereum is released and all commits have been pulled in.  This may turn into 1.9.0 depending on what upstream decides.

### CODE REVIEW

**Comment by detroitpro** [comment]
@seanjnkns - testing local today.

**Comment by detroitpro** [comment]
Working on the merge conflict. The root problem is that the new GraphQL API does not accept username/password (something that AKA added). I wonder if we should make the GraphQL API support username/password or if we should remove that feature from the AKA client.

Thoughts?

@seanjnkns @mkrufky

**Comment by seanjnkns** [comment]
Personally, I'd like to see us just drop 100% of the username/password stuff.  Makes merges easier and drops something that as seen from the announcement, few, if any are using.  With the removal of the MN program, I don't see any point in keeping this around as we can re-invent the MN setup based on what the network needs, including the systemd entries, etc.

**Comment by mkrufky** [comment]
IMHO, ditch user / pass ....   To my understanding, Akroma added this last year before I got involved as a measure to limit access to RPC services.  There are other ways to do this, and we have found this "feature" to create more problems than it had solved.

**Comment by seanjnkns** [comment]
Closing in favor of #93

**Pull request closed without merging**
